# Data Archival Configuration for Financial Platform
# Long-term storage and compliance requirements

# Archival Policies
archival_policies:
  # Transaction Data
  transaction_data:
    retention_period: "7 years"
    archival_trigger: "90 days"
    storage_class: "glacier"
    compression: true
    encryption: true
    
    # Data types
    data_types:
      - name: "payment_transactions"
        retention: "7 years"
        archival_frequency: "monthly"
        
      - name: "escrow_transactions"
        retention: "7 years"
        archival_frequency: "monthly"
        
      - name: "ledger_entries"
        retention: "7 years"
        archival_frequency: "monthly"
        
      - name: "audit_logs"
        retention: "7 years"
        archival_frequency: "weekly"

  # User Data
  user_data:
    retention_period: "5 years"
    archival_trigger: "1 year"
    storage_class: "glacier"
    compression: true
    encryption: true
    
    # Data types
    data_types:
      - name: "user_profiles"
        retention: "5 years"
        archival_frequency: "quarterly"
        
      - name: "kyc_documents"
        retention: "5 years"
        archival_frequency: "quarterly"
        
      - name: "compliance_reports"
        retention: "5 years"
        archival_frequency: "monthly"

  # Analytics Data
  analytics_data:
    retention_period: "3 years"
    archival_trigger: "6 months"
    storage_class: "glacier"
    compression: true
    encryption: true
    
    # Data types
    data_types:
      - name: "usage_analytics"
        retention: "3 years"
        archival_frequency: "monthly"
        
      - name: "performance_metrics"
        retention: "3 years"
        archival_frequency: "monthly"
        
      - name: "business_intelligence"
        retention: "3 years"
        archival_frequency: "quarterly"

# Archival Storage Configuration
archival_storage:
  # AWS S3 Glacier
  s3_glacier:
    enabled: true
    bucket: "financial-platform-archives"
    region: "us-east-1"
    storage_class: "GLACIER"
    
    # Lifecycle policies
    lifecycle_policies:
      - name: "transaction_archival"
        prefix: "transactions/"
        transition_days: 90
        expiration_days: 2555  # 7 years
        
      - name: "user_data_archival"
        prefix: "users/"
        transition_days: 365
        expiration_days: 1825  # 5 years
        
      - name: "analytics_archival"
        prefix: "analytics/"
        transition_days: 180
        expiration_days: 1095  # 3 years

  # Google Cloud Storage
  gcs_coldline:
    enabled: false
    bucket: "financial-platform-archives"
    storage_class: "COLDLINE"
    
    # Lifecycle policies
    lifecycle_policies:
      - name: "transaction_archival"
        prefix: "transactions/"
        age_days: 90
        action: "SetStorageClass"
        storage_class: "COLDLINE"

# Archival Process Configuration
archival_process:
  # Automated Archival
  automated:
    enabled: true
    schedule: "0 1 * * *"  # Daily at 1 AM
    
    # Archival jobs
    jobs:
      - name: "transaction_archival"
        schedule: "0 2 1 * *"  # Monthly on 1st at 2 AM
        data_source: "postgresql"
        query: |
          SELECT * FROM transactions 
          WHERE created_at < NOW() - INTERVAL '90 days'
          AND archived = false
        batch_size: 10000
        
      - name: "user_data_archival"
        schedule: "0 3 1 */3 *"  # Quarterly on 1st at 3 AM
        data_source: "mongodb"
        query: |
          db.users.find({
            "last_activity": {
              $lt: new Date(Date.now() - 365 * 24 * 60 * 60 * 1000)
            },
            "archived": false
          })
        batch_size: 5000
        
      - name: "analytics_archival"
        schedule: "0 4 1 */6 *"  # Every 6 months on 1st at 4 AM
        data_source: "mongodb"
        query: |
          db.analytics.find({
            "created_at": {
              $lt: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000)
            },
            "archived": false
          })
        batch_size: 10000

  # Manual Archival
  manual:
    enabled: true
    approval_required: true
    
    # Manual archival procedures
    procedures:
      - name: "Emergency Archival"
        description: "Immediate archival for compliance"
        requires_approval: false
        notification_channels: ["slack", "email"]
        
      - name: "Bulk Archival"
        description: "Large-scale archival operation"
        requires_approval: true
        notification_channels: ["slack", "email"]
        advance_notice: "24h"

# Data Retrieval Configuration
data_retrieval:
  # Retrieval Policies
  retrieval_policies:
    # Standard Retrieval
    standard:
      retrieval_time: "3-5 hours"
      cost_per_gb: 0.01
      notification: true
      
    # Expedited Retrieval
    expedited:
      retrieval_time: "1-3 hours"
      cost_per_gb: 0.03
      approval_required: true
      notification: true
      
    # Bulk Retrieval
    bulk:
      retrieval_time: "5-12 hours"
      cost_per_gb: 0.005
      approval_required: true
      notification: true

  # Retrieval Procedures
  retrieval_procedures:
    - name: "Compliance Retrieval"
      description: "Retrieve data for regulatory compliance"
      priority: "high"
      approval_required: false
      
    - name: "Legal Retrieval"
      description: "Retrieve data for legal proceedings"
      priority: "high"
      approval_required: true
      
    - name: "Business Retrieval"
      description: "Retrieve data for business analysis"
      priority: "medium"
      approval_required: true

# Compliance Requirements
compliance:
  # Regulatory Requirements
  regulatory:
    - regulation: "PCI DSS"
      requirement: "7 years retention"
      data_types: ["payment_transactions", "audit_logs"]
      archival_required: true
      
    - regulation: "SOX"
      requirement: "7 years retention"
      data_types: ["financial_records", "audit_logs"]
      archival_required: true
      
    - regulation: "GDPR"
      requirement: "Data minimization"
      data_types: ["user_data", "personal_information"]
      archival_required: true
      
    - regulation: "AML"
      requirement: "5 years retention"
      data_types: ["transaction_records", "kyc_documents"]
      archival_required: true

  # Audit Requirements
  audit:
    - type: "Internal Audit"
      frequency: "quarterly"
      scope: "Archival processes and data integrity"
      
    - type: "External Audit"
      frequency: "annually"
      scope: "Compliance with regulatory requirements"
      
    - type: "Security Audit"
      frequency: "annually"
      scope: "Archival security and access controls"

# Monitoring and Alerting
monitoring:
  # Archival Monitoring
  archival_monitoring:
    enabled: true
    metrics:
      - archival_success_rate
      - archival_duration_seconds
      - archival_size_bytes
      - retrieval_success_rate
      - retrieval_duration_seconds
      
    # Archival alerts
    alerts:
      - name: "ArchivalFailed"
        condition: "archival_success_rate < 95"
        severity: "warning"
        notification_channels: ["slack", "email"]
        
      - name: "ArchivalSizeHigh"
        condition: "archival_size_bytes > 107374182400"  # 100GB
        severity: "warning"
        notification_channels: ["slack"]
        
      - name: "RetrievalFailed"
        condition: "retrieval_success_rate < 90"
        severity: "critical"
        notification_channels: ["slack", "email", "pagerduty"]

# Data Integrity
data_integrity:
  # Integrity Checks
  integrity_checks:
    enabled: true
    schedule: "0 5 * * 0"  # Weekly on Sunday at 5 AM
    
    # Check types
    checks:
      - name: "Checksum Verification"
        description: "Verify data integrity using checksums"
        frequency: "weekly"
        
      - name: "Data Completeness"
        description: "Verify all required data is archived"
        frequency: "monthly"
        
      - name: "Accessibility Test"
        description: "Test data retrieval from archival storage"
        frequency: "quarterly"

  # Data Validation
  data_validation:
    enabled: true
    
    # Validation rules
    rules:
      - name: "Transaction Validation"
        description: "Validate transaction data before archival"
        fields: ["id", "amount", "currency", "timestamp", "status"]
        
      - name: "User Data Validation"
        description: "Validate user data before archival"
        fields: ["id", "email", "kyc_status", "created_at"]
        
      - name: "Analytics Validation"
        description: "Validate analytics data before archival"
        fields: ["id", "event_type", "timestamp", "user_id"]
