# Audit Logging Configuration for Financial Platform
# Comprehensive audit trail for regulatory compliance

# Audit Logging Framework
audit_logging:
  # Centralized Audit Service
  audit_service:
    enabled: true
    service_name: "audit-service"
    port: 8120
    log_level: "INFO"
    
    # Storage Configuration
    storage:
      type: "elasticsearch"
      index_pattern: "audit-logs-{YYYY.MM.DD}"
      retention_days: 2555  # 7 years for compliance
      compression: true
      encryption: true
      
    # Log Format
    log_format:
      timestamp: "ISO8601"
      correlation_id: true
      user_id: true
      session_id: true
      ip_address: true
      user_agent: true
      request_id: true

# Audit Events Configuration
audit_events:
  # Authentication Events
  authentication:
    - event_type: "user_login"
      severity: "INFO"
      required_fields: ["user_id", "ip_address", "user_agent", "success"]
      retention: "7 years"
      
    - event_type: "user_logout"
      severity: "INFO"
      required_fields: ["user_id", "session_id", "duration"]
      retention: "7 years"
      
    - event_type: "failed_login"
      severity: "WARNING"
      required_fields: ["user_id", "ip_address", "reason", "attempt_count"]
      retention: "7 years"
      
    - event_type: "password_change"
      severity: "INFO"
      required_fields: ["user_id", "ip_address", "method"]
      retention: "7 years"
      
    - event_type: "account_locked"
      severity: "WARNING"
      required_fields: ["user_id", "ip_address", "reason", "duration"]
      retention: "7 years"

  # Authorization Events
  authorization:
    - event_type: "permission_granted"
      severity: "INFO"
      required_fields: ["user_id", "resource", "permission", "granted_by"]
      retention: "7 years"
      
    - event_type: "permission_revoked"
      severity: "INFO"
      required_fields: ["user_id", "resource", "permission", "revoked_by"]
      retention: "7 years"
      
    - event_type: "access_denied"
      severity: "WARNING"
      required_fields: ["user_id", "resource", "permission", "reason"]
      retention: "7 years"
      
    - event_type: "role_assigned"
      severity: "INFO"
      required_fields: ["user_id", "role", "assigned_by"]
      retention: "7 years"
      
    - event_type: "role_removed"
      severity: "INFO"
      required_fields: ["user_id", "role", "removed_by"]
      retention: "7 years"

  # Financial Transaction Events
  financial_transactions:
    - event_type: "payment_initiated"
      severity: "INFO"
      required_fields: ["user_id", "transaction_id", "amount", "currency", "payment_method"]
      retention: "7 years"
      
    - event_type: "payment_completed"
      severity: "INFO"
      required_fields: ["user_id", "transaction_id", "amount", "currency", "status"]
      retention: "7 years"
      
    - event_type: "payment_failed"
      severity: "WARNING"
      required_fields: ["user_id", "transaction_id", "amount", "currency", "reason"]
      retention: "7 years"
      
    - event_type: "escrow_created"
      severity: "INFO"
      required_fields: ["user_id", "escrow_id", "amount", "currency", "terms"]
      retention: "7 years"
      
    - event_type: "escrow_released"
      severity: "INFO"
      required_fields: ["user_id", "escrow_id", "amount", "currency", "reason"]
      retention: "7 years"
      
    - event_type: "refund_processed"
      severity: "INFO"
      required_fields: ["user_id", "transaction_id", "amount", "currency", "reason"]
      retention: "7 years"

  # Data Access Events
  data_access:
    - event_type: "data_viewed"
      severity: "INFO"
      required_fields: ["user_id", "data_type", "record_id", "purpose"]
      retention: "7 years"
      
    - event_type: "data_exported"
      severity: "INFO"
      required_fields: ["user_id", "data_type", "record_count", "format"]
      retention: "7 years"
      
    - event_type: "data_modified"
      severity: "INFO"
      required_fields: ["user_id", "data_type", "record_id", "changes"]
      retention: "7 years"
      
    - event_type: "data_deleted"
      severity: "WARNING"
      required_fields: ["user_id", "data_type", "record_id", "reason"]
      retention: "7 years"
      
    - event_type: "bulk_operation"
      severity: "INFO"
      required_fields: ["user_id", "operation_type", "record_count", "affected_records"]
      retention: "7 years"

  # System Events
  system_events:
    - event_type: "service_started"
      severity: "INFO"
      required_fields: ["service_name", "version", "startup_time"]
      retention: "7 years"
      
    - event_type: "service_stopped"
      severity: "INFO"
      required_fields: ["service_name", "reason", "uptime"]
      retention: "7 years"
      
    - event_type: "configuration_changed"
      severity: "INFO"
      required_fields: ["service_name", "parameter", "old_value", "new_value", "changed_by"]
      retention: "7 years"
      
    - event_type: "backup_created"
      severity: "INFO"
      required_fields: ["backup_type", "size", "location", "checksum"]
      retention: "7 years"
      
    - event_type: "backup_restored"
      severity: "INFO"
      required_fields: ["backup_type", "restored_by", "verification_status"]
      retention: "7 years"

# Compliance Requirements
compliance_requirements:
  # PCI DSS Requirements
  pci_dss:
    enabled: true
    version: "4.0"
    
    # Requirement 10: Audit Logging
    requirement_10:
      - control: "10.1"
        description: "Implement audit logging"
        implementation: "Centralized audit service with comprehensive event capture"
        
      - control: "10.2"
        description: "Automated audit trails"
        implementation: "Real-time log collection and processing"
        
      - control: "10.3"
        description: "Audit log retention"
        implementation: "7-year retention with tamper-proof storage"
        
      - control: "10.4"
        description: "Time synchronization"
        implementation: "NTP synchronization across all systems"
        
      - control: "10.5"
        description: "Secure audit trails"
        implementation: "Encrypted storage with access controls"

  # SOX Requirements
  sox:
    enabled: true
    
    # Section 302: Corporate Responsibility
    section_302:
      - control: "302.1"
        description: "Financial data integrity"
        implementation: "Audit trails for all financial transactions"
        
      - control: "302.2"
        description: "Internal controls"
        implementation: "Comprehensive access and authorization logging"
        
      - control: "302.3"
        description: "Disclosure controls"
        implementation: "Audit trails for all data disclosures"

    # Section 404: Management Assessment
    section_404:
      - control: "404.1"
        description: "Internal control framework"
        implementation: "Automated control monitoring and reporting"
        
      - control: "404.2"
        description: "Control effectiveness"
        implementation: "Regular audit log analysis and reporting"

  # GDPR Requirements
  gdpr:
    enabled: true
    
    # Article 30: Records of Processing Activities
    article_30:
      - control: "30.1"
        description: "Processing records"
        implementation: "Comprehensive data processing audit trails"
        
      - control: "30.2"
        description: "Data subject rights"
        implementation: "Audit trails for data subject requests"
        
      - control: "30.3"
        description: "Data breaches"
        implementation: "Incident logging and notification tracking"

    # Article 32: Security of Processing
    article_32:
      - control: "32.1"
        description: "Security measures"
        implementation: "Security event logging and monitoring"
        
      - control: "32.2"
        description: "Access controls"
        implementation: "Comprehensive access audit trails"

  # AML Requirements
  aml:
    enabled: true
    
    # Customer Due Diligence
    cdd:
      - control: "CDD.1"
        description: "Customer identification"
        implementation: "KYC process audit trails"
        
      - control: "CDD.2"
        description: "Risk assessment"
        implementation: "Risk assessment audit trails"
        
      - control: "CDD.3"
        description: "Ongoing monitoring"
        implementation: "Transaction monitoring audit trails"

    # Suspicious Activity Reporting
    sar:
      - control: "SAR.1"
        description: "Suspicious activity detection"
        implementation: "Suspicious activity audit trails"
        
      - control: "SAR.2"
        description: "SAR filing"
        implementation: "SAR filing audit trails"

# Audit Log Processing
audit_log_processing:
  # Real-time Processing
  real_time_processing:
    enabled: true
    stream_processor: "kafka"
    batch_size: 100
    processing_latency: "< 1 second"
    
    # Event Enrichment
    event_enrichment:
      enabled: true
      enrichments:
        - name: "user_context"
          source: "user_service"
          fields: ["user_role", "user_permissions", "user_status"]
          
        - name: "geographic_context"
          source: "geo_service"
          fields: ["country", "region", "city", "timezone"]
          
        - name: "risk_context"
          source: "risk_service"
          fields: ["risk_score", "risk_level", "risk_factors"]

  # Batch Processing
  batch_processing:
    enabled: true
    schedule: "0 2 * * *"  # Daily at 2 AM
    
    # Aggregations
    aggregations:
      - name: "daily_user_activity"
        schedule: "0 3 * * *"
        metrics: ["login_count", "transaction_count", "data_access_count"]
        
      - name: "daily_system_activity"
        schedule: "0 4 * * *"
        metrics: ["service_errors", "performance_metrics", "security_events"]
        
      - name: "compliance_reporting"
        schedule: "0 5 * * 0"  # Weekly on Sunday
        metrics: ["pci_compliance", "sox_compliance", "gdpr_compliance"]

# Audit Log Storage
audit_log_storage:
  # Primary Storage (Elasticsearch)
  primary_storage:
    type: "elasticsearch"
    cluster_name: "audit-logs-cluster"
    nodes: 3
    shards: 5
    replicas: 1
    
    # Index Management
    index_management:
      rollover_size: "50GB"
      rollover_age: "30d"
      delete_after: "2555d"  # 7 years
      
    # Security
    security:
      encryption_at_rest: true
      encryption_in_transit: true
      access_control: true

  # Backup Storage (S3)
  backup_storage:
    type: "s3"
    bucket: "audit-logs-backup"
    region: "us-east-1"
    encryption: true
    lifecycle_policy: true

# Audit Log Monitoring
audit_log_monitoring:
  # Real-time Monitoring
  real_time_monitoring:
    enabled: true
    
    # Alerts
    alerts:
      - name: "HighAuditVolume"
        condition: "audit_events_per_minute > 10000"
        severity: "warning"
        notification_channels: ["slack", "email"]
        
      - name: "AuditProcessingDelay"
        condition: "processing_latency > 5 seconds"
        severity: "critical"
        notification_channels: ["slack", "email", "pagerduty"]
        
      - name: "AuditStorageFull"
        condition: "storage_usage > 90%"
        severity: "critical"
        notification_channels: ["slack", "email", "pagerduty"]
        
      - name: "SuspiciousActivity"
        condition: "suspicious_events > 10 in 5 minutes"
        severity: "critical"
        notification_channels: ["slack", "email", "pagerduty"]

  # Compliance Monitoring
  compliance_monitoring:
    enabled: true
    
    # Compliance Checks
    checks:
      - name: "PCICompliance"
        frequency: "daily"
        checks: ["audit_log_retention", "audit_log_integrity", "audit_log_access"]
        
      - name: "SOXCompliance"
        frequency: "weekly"
        checks: ["financial_audit_trails", "access_controls", "change_management"]
        
      - name: "GDPRCompliance"
        frequency: "daily"
        checks: ["data_processing_logs", "data_subject_rights", "data_breaches"]
        
      - name: "AMLCompliance"
        frequency: "daily"
        checks: ["transaction_monitoring", "suspicious_activity", "sar_filing"]

# Audit Log Reporting
audit_log_reporting:
  # Automated Reports
  automated_reports:
    - name: "DailyAuditSummary"
      schedule: "0 6 * * *"
      recipients: ["compliance@financialplatform.com"]
      format: "PDF"
      
    - name: "WeeklyComplianceReport"
      schedule: "0 7 * * 0"
      recipients: ["compliance@financialplatform.com", "legal@financialplatform.com"]
      format: "PDF"
      
    - name: "MonthlyAuditReport"
      schedule: "0 8 1 * *"
      recipients: ["compliance@financialplatform.com", "legal@financialplatform.com", "cto@financialplatform.com"]
      format: "PDF"

  # Ad-hoc Reports
  ad_hoc_reports:
    enabled: true
    retention: "7 years"
    
    # Report Types
    report_types:
      - name: "UserActivityReport"
        description: "User activity audit report"
        parameters: ["user_id", "date_range", "activity_type"]
        
      - name: "TransactionAuditReport"
        description: "Transaction audit report"
        parameters: ["transaction_id", "date_range", "amount_range"]
        
      - name: "DataAccessReport"
        description: "Data access audit report"
        parameters: ["data_type", "user_id", "date_range"]
        
      - name: "SecurityEventReport"
        description: "Security event audit report"
        parameters: ["event_type", "severity", "date_range"]
