version: '3.8'

services:
  # Infrastructure Services
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - financial_network

  consul:
    image: consul:latest
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0
    volumes:
      - consul_data:/consul/data
    healthcheck:
      test: ["CMD", "consul", "members"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - financial_network

  vault:
    image: vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: dev-token
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    volumes:
      - vault_data:/vault/data
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - financial_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - financial_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: false
    volumes:
      - grafana_data:/var/lib/grafana
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - financial_network

  # API Gateway
  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "8090:8090"
    environment:
      - ENVIRONMENT=production
    depends_on:
      - rabbitmq
      - consul
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8090/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - financial_network

  # Database Service
  database-service:
    build:
      context: .
      dockerfile: database-service/Dockerfile
    container_name: database-service
    ports:
      - "8115:8115"
    environment:
      - POSTGRES_URL=postgres://neondb_owner:npg_6oAPnbj5zIKN@ep-wispy-union-adi5og8a-pooler.c-2.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
      - MONGODB_URL=mongodb+srv://tendai_db_user:aEmut0m48FtaES1E@cluster0.csdtbuo.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - REDIS_URL=redis://localhost:6379
    depends_on:
      - rabbitmq
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8115/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - financial_network

  # Monitoring Service
  monitoring-service:
    build:
      context: .
      dockerfile: monitoring-service/Dockerfile
    container_name: monitoring-service
    ports:
      - "8116:8116"
    environment:
      - ENVIRONMENT=production
    depends_on:
      - prometheus
      - grafana
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8116/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - financial_network

  # Message Queue Service
  message-queue-service:
    build:
      context: .
      dockerfile: message-queue-service/Dockerfile
    container_name: message-queue-service
    ports:
      - "8117:8117"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - MONGODB_URL=mongodb+srv://tendai_db_user:aEmut0m48FtaES1E@cluster0.csdtbuo.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8117/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - financial_network

  # Service Discovery Service
  service-discovery:
    build:
      context: .
      dockerfile: service-discovery/Dockerfile
    container_name: service-discovery
    ports:
      - "8118:8118"
    environment:
      - CONSUL_ADDR=consul:8500
    depends_on:
      consul:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8118/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - financial_network

  # Vault Service
  vault-service:
    build:
      context: .
      dockerfile: vault-service/Dockerfile
    container_name: vault-service
    ports:
      - "8119:8119"
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=dev-token
    depends_on:
      vault:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8119/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - financial_network

  # Business Services
  escrow-service:
    build:
      context: .
      dockerfile: escrow-service/Dockerfile
    container_name: escrow-service
    ports:
      - "8081:8081"
    environment:
      - ENVIRONMENT=production
    depends_on:
      - database-service
      - message-queue-service
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - financial_network

  payment-service:
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    container_name: payment-service
    ports:
      - "8083:8083"
    environment:
      - ENVIRONMENT=production
    depends_on:
      - database-service
      - message-queue-service
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8083/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - financial_network

  ledger-service:
    build:
      context: .
      dockerfile: ledger-service/Dockerfile
    container_name: ledger-service
    ports:
      - "8084:8084"
    environment:
      - ENVIRONMENT=production
    depends_on:
      - database-service
      - message-queue-service
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8084/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - financial_network

  # Add more services as needed...
  # (I'll create a script to generate all the remaining services)

volumes:
  rabbitmq_data:
  consul_data:
  vault_data:
  prometheus_data:
  grafana_data:

networks:
  financial_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
