version: '3.8'

services:
  # Audit Service
  audit-service:
    image: financial-platform/audit-service:latest
    container_name: audit-service
    ports:
      - "8120:8120"
    volumes:
      - ./audit/config:/app/config
      - ./audit/logs:/app/logs
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - LOG_LEVEL=INFO
    networks:
      - compliance_network

  # Compliance Monitor
  compliance-monitor:
    image: financial-platform/compliance-monitor:latest
    container_name: compliance-monitor
    ports:
      - "8121:8121"
    volumes:
      - ./compliance:/app/config
    environment:
      - PROMETHEUS_URL=http://prometheus:9090
      - ALERTMANAGER_URL=http://alertmanager:9093
    networks:
      - compliance_network

  # Data Governance Service
  data-governance:
    image: financial-platform/data-governance:latest
    container_name: data-governance
    ports:
      - "8122:8122"
    volumes:
      - ./governance:/app/config
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - KAFKA_URL=kafka:9092
    networks:
      - compliance_network

  # Apache Atlas (Data Lineage)
  apache-atlas:
    image: apache/atlas:latest
    container_name: apache-atlas
    ports:
      - "21000:21000"
    environment:
      - ATLAS_SERVER_OPTS=-Xms1024m -Xmx2048m
    volumes:
      - atlas_data:/var/lib/atlas
    networks:
      - compliance_network

  # Elasticsearch (Audit Logs)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - compliance_network

  # Kibana (Audit Logs Visualization)
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - compliance_network

volumes:
  atlas_data:
  elasticsearch_data:

networks:
  compliance_network:
    driver: bridge
